version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: lazytwitter2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
